/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as token from "./token";
export type { token };
export type { IRobotTxt } from "./IRobotTxt";
export type { RobotTxt } from "./RobotTxt";
