/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lib from "./lib";
export type { lib };
import type * as src from "./src";
export type { src };
export * as factories from "./factories";
export type { Ownable } from "./lib/openzeppelin-contracts/contracts/access/Ownable";
export { Ownable__factory } from "./factories/lib/openzeppelin-contracts/contracts/access/Ownable__factory";
export type { ERC20 } from "./lib/openzeppelin-contracts/contracts/token/ERC20/ERC20";
export { ERC20__factory } from "./factories/lib/openzeppelin-contracts/contracts/token/ERC20/ERC20__factory";
export type { ERC20Burnable } from "./lib/openzeppelin-contracts/contracts/token/ERC20/extensions/ERC20Burnable";
export { ERC20Burnable__factory } from "./factories/lib/openzeppelin-contracts/contracts/token/ERC20/extensions/ERC20Burnable__factory";
export type { IERC20Metadata } from "./lib/openzeppelin-contracts/contracts/token/ERC20/extensions/IERC20Metadata";
export { IERC20Metadata__factory } from "./factories/lib/openzeppelin-contracts/contracts/token/ERC20/extensions/IERC20Metadata__factory";
export type { IERC20 } from "./lib/openzeppelin-contracts/contracts/token/ERC20/IERC20";
export { IERC20__factory } from "./factories/lib/openzeppelin-contracts/contracts/token/ERC20/IERC20__factory";
export type { IRobotTxt } from "./src/IRobotTxt";
export { IRobotTxt__factory } from "./factories/src/IRobotTxt__factory";
export type { RobotTxt } from "./src/RobotTxt";
export { RobotTxt__factory } from "./factories/src/RobotTxt__factory";
export type { IRobot } from "./src/token/IRobot";
export { IRobot__factory } from "./factories/src/token/IRobot__factory";
export type { Robot } from "./src/token/Robot";
export { Robot__factory } from "./factories/src/token/Robot__factory";
